"$schema" = 'https://starship.rs/config-schema.json'

# Палитра (для удобства чтения, можно менять тут)
# MINT_1 = "#c4fff9" (Самый светлый)
# MINT_2 = "#8afff2" (Средний)
# MINT_3 = "#4fffd3" (Основной фон директории)
# SAPLING = "#8fc91e" (Твой зеленый)
# DARK    = "#1d2230" (Темный фон терминала/текста)


format = """
[░](fg:#c4fff9)\
[▒](fg:#8afff2)\
[▓](fg:#4fffd3)\
[ 󰠃 ](bg:#4fffd3 fg:#1d2230)\
$directory\
[](fg:#4fffd3 bg:#8fc91e)\
$git_branch\
$git_status\
[](fg:#8fc91e bg:#1d2230)\
$nodejs\
$rust\
$golang\
$php\
[ $time ](bg:#1d2230 fg:#a3aed2)\
[](fg:#1d2230)\
\n$character"""

# Настройки модулей, чтобы цвета подхватились правильно

[directory]
style = "bg:#4fffd3 fg:#1d2230 bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
style = "bg:#8fc91e fg:#1d2230 bold"
format = "[ $symbol$branch ]($style)"

[git_status]
style = "bg:#8fc91e fg:#1d2230 bold"
format = "[$all_status$ahead_behind ]($style)"

[time]
disabled = false
time_format = "%R" # 24-hour format
style = "bg:#1d2230 fg:#a3aed2"
format = "[[  $time ](bg:#1d2230 fg:#a3aed2)]($style)"

# Языки (чтобы не ломали красоту, если появятся)
[nodejs]
style = "bg:#1d2230 fg:#8fc91e"
format = "[ $symbol($version) ]($style)"

[rust]
style = "bg:#1d2230 fg:#8fc91e"
format = "[ $symbol($version) ]($style)"

